services:
  php:
    container_name: pw-php
    build:
      context: ./devops/php/image
    volumes:
      - ./www:/var/www/html/
    ports:
      - 80:80
    networks:
      - pw-net
  mysql:
    container_name: pw-mysql
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./devops/bd/initdb:/docker-entrypoint-initdb.d
    networks:
      - pw-net
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: pw-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - pw-net

networks:
  pw-net:
