/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PwFooter {
        "baseUrl": string;
        "mapImageUrl"?: string;
    }
    interface PwHeader {
        "activeLink"?: string;
        "baseUrl": string;
        "brandHref"?: string;
        "brandImageUrl"?: string;
        "linkBaseUrl"?: string;
    }
}
declare global {
    interface HTMLPwFooterElement extends Components.PwFooter, HTMLStencilElement {
    }
    var HTMLPwFooterElement: {
        prototype: HTMLPwFooterElement;
        new (): HTMLPwFooterElement;
    };
    interface HTMLPwHeaderElement extends Components.PwHeader, HTMLStencilElement {
    }
    var HTMLPwHeaderElement: {
        prototype: HTMLPwHeaderElement;
        new (): HTMLPwHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "pw-footer": HTMLPwFooterElement;
        "pw-header": HTMLPwHeaderElement;
    }
}
declare namespace LocalJSX {
    interface PwFooter {
        "baseUrl"?: string;
        "mapImageUrl"?: string;
    }
    interface PwHeader {
        "activeLink"?: string;
        "baseUrl"?: string;
        "brandHref"?: string;
        "brandImageUrl"?: string;
        "linkBaseUrl"?: string;
    }
    interface IntrinsicElements {
        "pw-footer": PwFooter;
        "pw-header": PwHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pw-footer": LocalJSX.PwFooter & JSXBase.HTMLAttributes<HTMLPwFooterElement>;
            "pw-header": LocalJSX.PwHeader & JSXBase.HTMLAttributes<HTMLPwHeaderElement>;
        }
    }
}
